### ISSUE TITLE
When pasting anything, I get every output 13x to console.log

### ISSUE THREAD

**Issue by jmuheim** [layerssss/paste.js#13]
When pasting anything, I get every output 13x to console.log. The text "getrennte" was pasted once and output 13x:

![image](https://cloud.githubusercontent.com/assets/1814983/8233670/d2baab48-15d7-11e5-8bf7-4419f4c03be0.png)

Is this correct? What could be the problem?

**Comment by jmuheim** [comment]
Yeah, what a nice coincidence: this is issue number 13! :laughing:

**Comment by layerssss** [comment]
no way, I cannot reproduce the problem, can you make a simple jsfiddle or gist to demonstrate the problem? that would be really helpful! :smile:

**Comment by jmuheim** [comment]
It seems to have to do with the `$('*')` selector from the example:

```coffee
  $('*').on('pasteImage', (ev, data) ->
    # ...
```

It seems to somehow traverse all the parent nodes of the textarea and appends the `<div>` to each node.

When doing

```coffee
  $('textarea#boilerplate_intro').on('pasteImage', (ev, data) ->
    # ...
```

it seems to work. But I don't want to specify a fixed ID, I want to target all the textareas I have.

If this doesn't help yet, I will create a CodePen for it.
