### ISSUE TITLE
not working in firefox 41.0.2

### ISSUE THREAD

**Issue by CMTietgen** [layerssss/paste.js#16]
I'm trying to paste images in FF 41.0.2, but it looks like it worked in FF 38. Have they done something to prevent this now?

Getting an image paste to work in all browsers without a Java applet is challenging to say the least.

**Comment by layerssss** [comment]
@CMTietgen thanks for telling me that, i think there were some minor changes in FF, I'm going to look into it, hopefully i'll fix the hack

**Comment by layerssss** [comment]
@CMTietgen Hi, I am unable to reproduce the problem on my firefox41 (OSX, El Capitan). Which platform are you using? Are you using Windows and which version of it?

![image](https://cloud.githubusercontent.com/assets/1559832/10874548/7755ee70-8161-11e5-8910-8332ecee3ac0.png)

**Comment by CMTietgen** [comment]
It's odd, I just tried again and it is working. I am not sure why it didn't when I originally reported this issue, but it looks like you can close this thread.

Thanks for looking into it and thanks for the code. I have an idea to use it in a website I am working on and will give you credit. I just need to figure out how to convert the blob data to an actual image and save it to the server.

**Comment by layerssss** [comment]
@CMTietgen No worry buddy. You can attach the blob to xhr via `FormData` (xhr2). Then it would just be like a file uploaded via `input[type='file']`. See this article http://www.html5rocks.com/en/tutorials/file/xhr2/
