### ISSUE TITLE
Doesn't work on Edge

### ISSUE THREAD

**Issue by nevf** [layerssss/paste.js#17]
The on 'pasteImage' event never fires on M Edge.

**Comment by layerssss** [comment]
![image](https://cloud.githubusercontent.com/assets/1559832/11096928/7e7113d8-88d7-11e5-8c43-a619a8123d9c.png)

Hi, @nevf , I tried it in Edge, and it works without a problem. I'll be better if you can show me your code, and let's see what is wrong

**Comment by nevf** [comment]
@layerssss Sorry I should have been more specific. It works of you Copy an Image in the Browser, and Paste that. However if you open an image from Windows Explorer in an Image Viewer (ex. Photos in Win10) Copy that, then Paste doesn't work. I am using your example page.
