### ISSUE TITLE
Thanks for the helpfull plugin!

### ISSUE THREAD

**Issue by superdummy** [layerssss/paste.js#20]
As there is no other easy way of doing this (ticket can be closed): 

I just wanted to say thank you for developing and maintaining this cool plugin. I will use it in a non profit project and it saves me lot of time as I am not javascript geek. So thanks very much for making this world a better place by sharing such great and helpfull code!!

**Comment by layerssss** [comment]
Wow, cheers mate! Keep the good works up!
