### ISSUE TITLE
does it work on Windows OS ?

### ISSUE THREAD

**Issue by IAIAE** [layerssss/paste.js#30]
你好！在rubyChina上看到你的帖子。貌似两年过去了clipboardData这个接口一点变化也没有~TAT~
***这个在windows系统上work嘛？*** clipboardData在自己mac上工作得挺好的，换到windows系统上复制图片后clipboardData.items.length为0。你是否遇到这类情况？

**Comment by layerssss** [comment]
Yes it will work on Windows, on Windows it will use the `contenteditable` hack to handle the images as well.
