### ISSUE TITLE
在firefox 45.3.0的contentEditable（输入）框中仅能保持一张图片

### ISSUE THREAD

**Issue by jaiiye** [layerssss/paste.js#31]
一块文本域中使用paste.js处理粘贴上传，然后将图片插入文本域，但在firefox中会把框中所有前面插入的图片清掉，看源码应该是方法_checkImagesInContainer将图片删掉了，如下：
![image](https://cloud.githubusercontent.com/assets/463148/17843243/4471e89e-685e-11e6-81b9-24482eb50e3f.png)。

**Comment by layerssss** [comment]
Good catch! It's fixed now! ✨
