### ISSUE TITLE
DataTransfer is not defined in all browsers

### ISSUE THREAD

**Issue by pkaminski** [layerssss/paste.js#32]
I think you need to checkof `typeof DataTransfer !== 'undefined'` before checking if it has an `items` property.

**Comment by layerssss** [comment]
Thanks buddy 😆  good catch!

**Comment by pkaminski** [comment]
Thanks for the fix, but I have bad news: it breaks in IE10 (and older, presumably):
`TypeError: Object doesn't support property or method '__lookupGetter__'`

I hate IE as much as the next person, but it would probably still be good if Reviewable didn't crash immediately on load if you're stuck using IE10 for some reason.

**Comment by layerssss** [comment]
@pkaminski I'll fix that quickly, and it seems that I have to set up a cross-browsers CI for not breaking behaviours of the current browser elements.

**Comment by pkaminski** [comment]
No problem, thanks!

**Comment by layerssss** [comment]
@pkaminski I've shipped the fix with 0.0.21. :)
