### ISSUE TITLE
About package on npm

### ISSUE THREAD

**Issue by pvnr0082t** [layerssss/paste.js#33]
Hi @layerssss ,
I'm a member of [cdnjs](https://github.com/cdnjs/cdnjs). We want to host this library.
I'd like to confirm that if https://www.npmjs.com/package/paste.js is officially maintained. If not, we will set git auto-update config and auto-updater in cdnjs will update automatically from git repo not NPM.
Thank you.

https://github.com/cdnjs/cdnjs/issues/9156

**Comment by layerssss** [comment]
HI @pvnr0082t that sounds so nice. The `npm` package is not maintained since it's just a single-file JavaScript library to be used in the browser. So updating it from the git repo makes more sense. Please let me know if you have any questions. :) 👍

**Comment by pvnr0082t** [comment]
@layerssss Pull reqeust just sent to cdnjs. Thanks for your help. :facepunch: 

https://github.com/cdnjs/cdnjs/pull/9179
