### ISSUE TITLE
Doesn't work in Chrome 55.0.2883.87 m

### ISSUE THREAD

**Issue by Wavum** [layerssss/paste.js#34]
It doesn't work for me in Chrome 55.0.2883.87 m.

**Comment by layerssss** [comment]
@Wavum Can you post more details of what issues are you having?

**Comment by Wavum** [comment]
@layerssss  I tested it on your website: http://gh-pages.micy.in/paste.js/

I don't get any errors, i just doesn't fire the pasteImage-event.
In firefox it work's for me.

**Comment by Wavum** [comment]
Ok, I tested it on another PC it's just my problem.

**Comment by layerssss** [comment]
@Wavum Maybe it has to do with the **image source** from which you copied, it can only be "an image", NOT "an image file", NOT any other type of non standard image.

I'm closing this now, feel free to reopen it if you discovered any more details need to be addressed.
