### ISSUE TITLE
Event pasteImage is called multiple times

### ISSUE THREAD

**Issue by salvisb** [layerssss/paste.js#37]
Hello!
When using pastableNonInputable() method, the event pasteImage is called multiple times.
In fact, there is a strange behavior, it looks like pasteImage is fired so much times as binded element goes into DOM.

To ilustrate:
$('html').pastableNonInputable();  // pasteImage is fired 1 time
$('body').pastableNonInputable();  // pasteImage is fired 2 times
$('#some_element_inside_body').pastableNonInputable();  // pasteImage is fired 3 times

```
$"html").pastableNonInputable();
$('*').on("pasteImage", function (ev, data) {
	var postData = {};
	postData.blob = true;
	postData.url = data.dataURL;
	$.post("/libraries/file_uploader/temporary",
		postData
	, function (data) {

	}, "json");
});
```

Is this behavior intended?

**Comment by layerssss** [comment]
Hi @salvisb      🤣   

I'm not surprised strange thing happening if you call the API on `html` or `body`, it's designed to be called on individual small DOM element. Like a `textarea`, or a `div` displayed as a rectangle.

**Comment by salvisb** [comment]
I want to intercept paste event every time it is fired, no matter which element is focused.
What would be the right way to achieve this?

**Comment by layerssss** [comment]
@salvisb If that's the case, maybe you need to listen to `paste` event without calling the `pastableNonInputable()`, that is to use the browers' original API. You will still able to get the image data in Chrome in this way by `event.clipboardData.items[0].getAsFile()`.

**Comment by layerssss** [comment]
For in IE and Firebox what this library is doing is just a bunch of hacks,   if you put the hacks on the parent / ancestry elements the hacks will do wield things :P

**Comment by salvisb** [comment]
@layerssss ok, thanks! If at some point current implementation will crush for my project needs, will look at `event.clipboardData.items[0]`
