### ISSUE TITLE
Safari currently supports this

### ISSUE THREAD

**Issue by eduo** [layerssss/paste.js#42]
In the past I hadn't been able to use this because of Safari.

Today I was looking and saw several snippets where image paste works in Safari:
https://jsfiddle.net/SaschaKluth/togafu5s/1/
http://jsfiddle.net/KJW4E/754/

So I revisited this and found out that the table still doesn't list Safari but that it indeed supports it 
in all three modes:

![screenshot 2017-04-20 17 13 02](https://cloud.githubusercontent.com/assets/154630/25238063/a28dcc4e-25ec-11e7-81db-cc378011c8ab.png)

Perhaps you'd like to update the table? I tested with Safari Version 10.1 (12603.1.30.0.34). Haven't tried with versions older than Sierra's but I could confirm with El Capitan's later today.

**Comment by layerssss** [comment]
Hi @eduo thanks for finding this! I've added the change to READMEs c6487b9 . Cheers.

**Comment by jmuheim** [comment]
That's great news! 👍
