### ISSUE TITLE
Update the npm package

### ISSUE THREAD

**Issue by silverwind** [layerssss/paste.js#46]
Would it be possibly to have https://www.npmjs.com/package/paste.js updated?

It would make it easier for me if new releases where published to npm so I don't have to rely on a possible unstable git dependency.

If you have no control over the package, I'm sure npm support can set you up as the owner.

**Comment by layerssss** [comment]
I've sent an email to the guy who put it up on npmjs. Hopefully he can add me to the collaborators list soon.

**Comment by layerssss** [comment]
@silverwind I believe I've published `paste.js@0.0.21`. It should be available for webpack-like tools now. Let me know if I'm missing anything.

**Comment by silverwind** [comment]
Package looks fine, thanks!
