### ISSUE TITLE
Why isn't Opera with "ok"s in the browser compatibility matrix?

### ISSUE THREAD

**Issue by mb13** [layerssss/paste.js#47]
Thanks for this plugin, it works perfectly for me :)

I just have one question. I'm using the `.pastableTextarea()` on `textarea` and I'm using `pasteImage` and it works for me also in Opera. The image is loaded from the clipboard for me.

**Comment by layerssss** [comment]
Hmm, thanks for telling me. I'll test it in the weekend and amend the table. That's a good news.

**Comment by mb13** [comment]
anyway, it also works for me in Edge ;-)

**Comment by layerssss** [comment]
@mb13 I've updated the support matrix :)
