### ISSUE TITLE
How can I trigger "pasteImage" on button click?

### ISSUE THREAD

**Issue by mb13** [layerssss/paste.js#50]
The CTRL-V functionality in textarea is working for me for images. But I would like to add a new button that would do the same job: it means if user clicks on it, it would take the content of the clipboard and would send me the required data. Is it possible to do that?

**Comment by layerssss** [comment]
Hi @mb13 , I don't think it's possible. Because the web content shouldn't be able to get OS clipboard content without explicit user instruction (CTRL/CMD - V). Otherwise it would be a security / privacy concern.
