### ISSUE TITLE
【Question】How about compatibility of Microsoft Edge?

### ISSUE THREAD

**Issue by SatoshiKawabata** [layerssss/paste.js#53]
[Browser compatibility](https://github.com/layerssss/paste.js#browser-compatibility) doesn't include Edge.
Please tell me compatibility of Microsoft Edge.

**Comment by layerssss** [comment]
@SatoshiKawabata Edge has being supported well! :) I shall add that to the matrix later.

**Comment by SatoshiKawabata** [comment]
Thanks. Very good.
