### ISSUE TITLE
pasted image's filename

### ISSUE THREAD

**Issue by leviwheatcroft** [layerssss/paste.js#65]
Is there any way to get the pasted image's filename ?

Seems like there must be some way to do this, as I've seen apps like slack show an image's filename when pasted.

I thought it might be in the image's exif data, but that doesn't seem to be the case.

**Comment by aYellowApple** [comment]
I thought, this is a paste of pictures from the clipboard, which is only a temporary file flow.
Do not have a file name in this form?

**Comment by leviwheatcroft** [comment]
I understand what you're saying, but how do other js apps get filenames from pasted images ?

**Comment by miladd3** [comment]
you can get file name like this

                chatTextarea.one('pasteImage', function (ev, data) {
                    var fileName = data.name;
                }).on('pasteImageError', function (ev, data) {
                    throw "error on pasting image";
                })

**Comment by leviwheatcroft** [comment]
I eventually realised that the "other js apps" I was thinking of (like slack.com) don't get a filename when, as others have said, there is no "file" to have a name. Instead, they just make up a name like "Image.jpg"
